// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTzVPzbJxq6bXCK9qTYYTuI5R9mAWLIR0',
    appId: '1:258922758117:web:4f1ad1b22c7da41a96f90c',
    messagingSenderId: '258922758117',
    projectId: 'fir-demo-805b3',
    authDomain: 'fir-demo-805b3.firebaseapp.com',
    storageBucket: 'fir-demo-805b3.firebasestorage.app',
    measurementId: 'G-LK5V4KNJ7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXCe_bgRrntPtI91Vol9OTzSfaM_KHo-o',
    appId: '1:258922758117:android:3814a3c9433d0a5e96f90c',
    messagingSenderId: '258922758117',
    projectId: 'fir-demo-805b3',
    storageBucket: 'fir-demo-805b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVSTx7LGm0RMhuseiqAGB5b4gdNCTUcWE',
    appId: '1:258922758117:ios:b1a88cb3505ffb0196f90c',
    messagingSenderId: '258922758117',
    projectId: 'fir-demo-805b3',
    storageBucket: 'fir-demo-805b3.firebasestorage.app',
    iosBundleId: 'com.example.tannie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVSTx7LGm0RMhuseiqAGB5b4gdNCTUcWE',
    appId: '1:258922758117:ios:b1a88cb3505ffb0196f90c',
    messagingSenderId: '258922758117',
    projectId: 'fir-demo-805b3',
    storageBucket: 'fir-demo-805b3.firebasestorage.app',
    iosBundleId: 'com.example.tannie',
  );
}
